### ISSUE TITLE
Allow sign in with GitHub to save code

### ISSUE THREAD

**Issue by eliutdev** [midudev/codi.link#100]

**Comment by dartilesm** [comment]
@eliutgon are you working on it?

**Comment by eliutgon** [comment]
> @eliutgon are you working on it?

No, it is only a proposal.  Since it is a big change I think it is better that I do it @midudev

**Comment by dartilesm** [comment]
@eliutgon I think is a good challenge, maybe we can try to do it. 
Although our change may not be merged, we will learn from @midudev 's review

**Comment by dartilesm** [comment]
I will take this issue. I'm currently working on it. 🐙🐈
