### ISSUE TITLE
Add timeout to tooltip after few seconds to remove it

### ISSUE THREAD

**Issue by diegogb-08** [midudev/codi.link#103]
When you hover the sidebar buttons, the tooltip stays there as long as you have the mouse over, but I think it would be better if the tooltip disappear after 5 seconds

**Comment by diegogb-08** [comment]
I have opened a PR to fix this issue: https://github.com/midudev/codi.link/pull/104 I hope you like it. This is actually my first PR ever in an open source project :)

**Comment by dartilesm** [comment]
> When you hover the sidebar buttons, the tooltip stays there as long as you have the mouse over, but I think it would be better if the tooltip disappear after 5 seconds

Hi @diegogb-08 , why do you think that is wrong? I think it is the normal behavior of tooltips. In fact, in visual studio, it does not disappear until the cursor leaves the element.
![vscode](https://user-images.githubusercontent.com/21966352/135773979-0d2f2a3a-10e0-4ed9-9de0-d2c06708da11.gif)



> I have opened a PR to fix this issue: #104 I hope you like it. This is actually my first PR ever in an open source project :)

It's also my first time collaborating on open source projects. Congrats!!

**Comment by diegogb-08** [comment]
Actually you are right, even though my vscode does not act the same way you show on the video. However, I still think that it is a bit annoying to have the tooltip there forever and I think the fact that it disappears or appears after few seconds gives a better UX because it is not covering forever part of text from the menu. It might be me with my OCD :).

**Comment by stylessh** [comment]
It's not a critical requested feature, but it helps to the experience anyway. Let's see if it got accepted!
