### ISSUE TITLE
Problem when load existing project on firefox navigator.

### ISSUE THREAD

**Issue by LucianoRicardo737** [midudev/codi.link#111]
When create a project and shared. Firefox load javascript code in html section.

**Comment by LucianoRicardo737** [comment]
Fixed by @pasagedev

**Comment by LucianoRicardo737** [comment]
Still not working @pasagedev.

![Captura de pantalla de 2021-10-31 12-57-10](https://user-images.githubusercontent.com/77549826/139591881-7335e89c-0a44-4396-b143-6b6264458fce.png)

![Captura de pantalla de 2021-10-31 12-56-37](https://user-images.githubusercontent.com/77549826/139591866-7136f2dd-b3a6-42ac-a6c7-b58ca6b39be5.png)

**Comment by pasagedev** [comment]
> 
> 
> Still not working @pasagedev.
> 
> ![Captura de pantalla de 2021-10-31 12-57-10](https://user-images.githubusercontent.com/77549826/139591881-7335e89c-0a44-4396-b143-6b6264458fce.png)
> 
> ![Captura de pantalla de 2021-10-31 12-56-37](https://user-images.githubusercontent.com/77549826/139591866-7136f2dd-b3a6-42ac-a6c7-b58ca6b39be5.png)

The PR is not merge yet, but in [the preview](https://codi-link-git-fork-pasagedev-fix-previous-in-26c043-midudev-pro.vercel.app/) you can try it. I tried it right now and works.

**Comment by LucianoRicardo737** [comment]
> > Still not working @pasagedev.
> > ![Captura de pantalla de 2021-10-31 12-57-10](https://user-images.githubusercontent.com/77549826/139591881-7335e89c-0a44-4396-b143-6b6264458fce.png)
> > ![Captura de pantalla de 2021-10-31 12-56-37](https://user-images.githubusercontent.com/77549826/139591866-7136f2dd-b3a6-42ac-a6c7-b58ca6b39be5.png)
> 
> The PR is not merge yet, but in [the preview](https://codi-link-git-fork-pasagedev-fix-previous-in-26c043-midudev-pro.vercel.app/) you can try it. I tried it right now and works.

Sorry, I thought I was depressed. It works perfect. Thanks!
