### ISSUE TITLE
Feature: only scroll the skypack results

### ISSUE THREAD

**Issue by javigaralva** [midudev/codi.link#160]
Now, if the user scrolls down to see the results and needs to input a new term, the user needs to scroll up again, This is annoying and, of course, this is wrong :unamused: 

It could be nice if the top part is sticked (the yellow part) and only the results can be scrolled (the red arrows):
![image](https://user-images.githubusercontent.com/21366112/137112589-2a4575ee-e25b-4b13-bbc9-87ad630b031b.png)

Can any **_css-master-hacker_** take this feature? :smile:

**Comment by midudev** [comment]
Implemented on #113.
