### ISSUE TITLE
When you want to use target pseudo class it happens this.

### ISSUE THREAD

**Issue by imollm** [midudev/codi.link#163]
https://user-images.githubusercontent.com/31571394/137353956-19996ab8-2c05-42c2-b86a-427b5c26c093.MOV

**Comment by StyvenSoft** [comment]
Calm down guys with @midudev tool that I don't think will turn it into a VSC.

**Comment by fredoist** [comment]
It is working fine for me; do you still have this issue @imollm?

https://user-images.githubusercontent.com/7684330/163026953-dddd7796-f865-4aab-9716-d006f5ad5262.mp4

**Comment by imollm** [comment]
> It is working fine for me; do you still have this issue @imollm?
> 
>  codi.link._.HTML.CSS.JavaScript.Live.Editor.Playground.-.12.April.2022.mp4

Yes now it works smoothly 😃
