### ISSUE TITLE
Iframe flickering when updating (MSEdge)

### ISSUE THREAD

**Issue by santi28** [midudev/codi.link#18]
In MSEdge the iframe flickering when updated

------- Browser Information -------
Browser: MSEdge
Versión: 92.0.902.67
------- System Information -------
OS: Windows 10
Version: 20H2

_In Chrome the flickering is minimal and it is not noticeable_

**Comment by midudev** [comment]
@santi28 could you please check if this issue is fixed with the @javigaralva Pull Request? Thanks!

**Comment by santi28** [comment]
@midudev Now the iframe flickering is very reduced as in chrome. It is present, but does not represent a great inconvenience
