### ISSUE TITLE
href="#" duplicates the page into the previewer

### ISSUE THREAD

**Issue by BobbyESP** [midudev/codi.link#180]
When having an href with the value of "#", the hole codi.link page gots duplicated into the web previewer.

https://user-images.githubusercontent.com/60316747/141383048-f0dfe00b-7b1f-43a8-92df-89192674e554.mp4

**Comment by QuevedoIB** [comment]
This issue is a duplicate of #163

**Comment by midudev** [comment]
Duplicated
