### ISSUE TITLE
Large code will not work

### ISSUE THREAD

**Issue by nullxx** [midudev/codi.link#191]
The share button creates a link as: https://codi.link/<BASE_64> can induce an [http 414 error](https://developer.mozilla.org/en-US/docs/Web/HTTP/Status/414)

## How to try it
- Create a script very large and try to copy the sharable url and open in another tab. 
- The connection gets refushed.

**Comment by davbrito** [comment]
I think this is an expected limitation of the current implementation.

There will always be this problem unless we use some backend to store the code instead of the URL as the source of the data.
