### ISSUE TITLE
Resize does not work very well 

### ISSUE THREAD

**Issue by Renato6GS** [midudev/codi.link#195]
😢
![image](https://user-images.githubusercontent.com/67927947/152285864-76e58c80-b75f-45ab-be32-2f9f9138c9dd.png)

**Comment by Renato6GS** [comment]
I have retested the codi.link in other browsers, and it seems to work fine. I normally use Microsoft Edge, however this does not work, and I think it is due to a browser extension, since in InPrivate mode it works correctly.

If someone has the following extension, codi.link may not work correctly for them:
- Adblock
- Nightmode
- Return Youtube Dislike
- Font Finder
- Super Dark Mode

**Comment by davbrito** [comment]
I had a problem with the resize and it was solved by cleaning the local storage. I don't know what was the cause but that's the workaround.

**Comment by Renato6GS** [comment]
:o thanks, that worked for me, but, I think I found the culprit.

When I set another "Editor Layout", resize does not work again, and I have to clean local storage to get it working again.
![image](https://user-images.githubusercontent.com/67927947/152480186-8d59c5c3-fed3-4c5d-b199-6da898c440b9.png)

Can you try it on your won machine? please

**Comment by davbrito** [comment]
@Renato6GS You're right. It seems to only work the the layout has not been changed before.

**Comment by davbrito** [comment]
@Renato6GS I fixed it on #197. I hope @midudev merges it soon.

**Comment by Renato6GS** [comment]
@davbrito Great! Thanks 😁
