### ISSUE TITLE
Changelog button covers the settings button

### ISSUE THREAD

**Issue by davbrito** [midudev/codi.link#199]
It's more annoying when using the compact sidebar style. But with the default it is still a bit large.

With the compact sidebar style:
![image](https://user-images.githubusercontent.com/39559632/152572600-cce2856a-894e-4508-ac4d-d930a628186a.png)

With default sidebar style:
![image](https://user-images.githubusercontent.com/39559632/152572664-ea998836-c4cc-4dcb-a47a-9a2fbf27cb57.png)

**Comment by fredoist** [comment]
Had the same issue with the Headway widget, especially with the compact sidebar. I feel like *20 pixels* is best for the widget size either with default or compact sidebar size. It leaves enough space to make the widget clickable but does not interfere with the settings icon.

With default sidebar:
![2022-04-12 (2)](https://user-images.githubusercontent.com/7684330/163022418-ca1eed81-485a-4844-9bc0-d7b735e6c17f.png)
![2022-04-12 (1)](https://user-images.githubusercontent.com/7684330/163022420-8df16e6d-be1b-41d5-958d-bd6ad389cb88.png)

With compact sidebar:
![2022-04-12](https://user-images.githubusercontent.com/7684330/163022452-c104e33c-b852-4b38-93e3-f4450319bbb6.png)
![2022-04-12 (3)](https://user-images.githubusercontent.com/7684330/163022455-5ff788c5-2635-453e-bcaa-8d99b08b3375.png)
