### ISSUE TITLE
Integrate Skypack.dev

### ISSUE THREAD

**Issue by pheralb** [midudev/codi.link#20]
Use [Skypack.dev](https://www.skypack.dev/) to import NPM packages into codi.link:

- Import package -> https://cdn.skypack.dev/package-name
- Import package but minified -> https://cdn.skypack.dev/package-name?min

Code in the JS box (example):

`import React from "https://cdn.skypack.dev/react";`
`import chakraUiLayout from 'https://cdn.skypack.dev/@chakra-ui/layout';`

Example:
![image](https://user-images.githubusercontent.com/62877300/132904908-b65f8bf8-08c5-4c71-85a9-d587937d7a11.png)

URL: https://bit.ly/3ho9WSt

**Comment by eliutgon** [comment]
@midudev @pheralb 
I have been working on this 

https://user-images.githubusercontent.com/63687573/133783999-938ceef8-f188-42ef-92bf-6bb255c01ee8.mp4

**Comment by midudev** [comment]
Do a PR @eliutgon  :D

**Comment by eliutgon** [comment]
@midudev #44
