### ISSUE TITLE
Editor is not resized

### ISSUE THREAD

**Issue by pana9422** [midudev/codi.link#206]
Don't allow resizing when js editor is fully expanded
![image](https://user-images.githubusercontent.com/88917568/175340573-1a0e62c5-8461-4722-818f-ea0107d61869.png)

**Comment by jasael** [comment]
This is the configuration of the layout and the error you are reporting
![image](https://github.com/user-attachments/assets/e10120f8-4feb-4b96-8fed-bce0a3bb7e86)

**Comment by jasael** [comment]
In both layouts (fully vertical and fully horizontal) it generates the same error when the JS editor is fully expanded.
![image](https://github.com/user-attachments/assets/1b8f2c14-9b6e-42b0-9017-c774d13c4c6e)
