### ISSUE TITLE
Fix autocompletado de Emmet 

### ISSUE THREAD

**Issue by JoaquinLoiza** [midudev/codi.link#219]
**El autocompletado de Emmet para HTML dejó de funcionar!**

**Comment by nachobalo** [comment]
Es un problema con el monaco-editor, lo solucione con la version 0.22. Solo eso.

**Comment by yebt** [comment]
Hola, disculpe, ¿Como puedo acceder a la versión 0.22?

**Comment by nachobalo** [comment]
Descargas el proyecto vas a package.json, buscas la dependencia monaco-editor creo q esta en la version 0.34 o superior. Cambias ese numero a 0.22. npm install y con eso deberia dejar de dar problemas. Yo lo tengo funcionando.

**Comment by yebt** [comment]
> Descargas el proyecto vas a package.json, buscas la dependencia monaco-editor creo q esta en la version 0.34 o superior. Cambias ese numero a 0.22. npm install y con eso deberia dejar de dar problemas. Yo lo tengo funcionando.

Muchísimas gracias
