### ISSUE TITLE
La consola implementada en el Sidebar no es muy eficiente

### ISSUE THREAD

**Issue by GintokiYT** [midudev/codi.link#239]
La consola proporcionada no esta bien implementada, estaba mejor cuando se podia ver los cambios en la consola del propio navegador.
![consola](https://github.com/midudev/codi.link/assets/72818352/9712e03a-59e3-4a6d-baa0-872f93b65120)

**Comment by andymedina1** [comment]
Sería bueno que la consola mostrara el undefined como en la consola de chrome y no solo un espacio vacío

![image](https://github.com/midudev/codi.link/assets/107598069/799b9ae0-6d95-4835-8b95-4e8ef987d8bf)

**Comment by SalvadorSru** [comment]
Directamente yo eliminaría la consola del sidebar, es un claro ejemplo de que no hacía falta arreglar algo que no estaba roto.

La consola nativa del navegador iba perfectamente estaba integrada con todos los tipos de datos y las referencias de elementos y mucho más personalizable.
