### ISSUE TITLE
Reloading the page doesn't work as spected

### ISSUE THREAD

**Issue by AngelNext** [midudev/codi.link#30]
https://user-images.githubusercontent.com/79442303/131915746-8b191fe1-3fb9-49e6-a3cb-c647fa3b4132.mp4

**Comment by javigaralva** [comment]
Please, could you provide an example to test (an url or the css, js and html code). Thanks

**Comment by AngelNext** [comment]
**The code that I use in the video**: https://codi.link/PCFET0NUWVBFIGh0bWw+DQo8aHRtbCBsYW5nPSJlbiI+DQo8aGVhZD4NCiAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+DQogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPg0KICAgIDx0aXRsZT5FeGFtcGxlPC90aXRsZT4NCjwvaGVhZD4NCjxib2R5Pg0KICAgIDxwcmUgaWQ9ImNvZGUiPjwvcHJlPg0KPC9ib2R5Pg0KPC9odG1sPg==|I2NvZGUgew0KICAgIGZvbnQtZmFtaWx5OiAnQ2FzY2FkaWEgQ29kZSc7DQp9DQoNCmJvZHkgew0KICAgIGNvbG9yOiByZ2IoMjA5LCAxOTgsIDE5OCk7DQogICAgYmFja2dyb3VuZDogcmdiKDI0LCAyNCwgMjQpDQp9|ZmV0Y2goJ2h0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9wcm9kdWN0cycpDQogIC50aGVuKHJlcyA9PiByZXMuanNvbigpKQ0KICAudGhlbihkYXRhID0+IHsNCiAgICAgIGRvY3VtZW50LmdldEVsZW1lbnRCeUlkKCJjb2RlIikuaW5uZXJUZXh0ID0gSlNPTi5zdHJpbmdpZnkoZGF0YSwgbnVsbCwgMikNCiAgIH0pDQogICAuY2F0Y2goZXJyID0+IGNvbnNvbGUuZXJyb3IoZXJyKSk=

**Comment by javigaralva** [comment]
I changed the code to fetch other api (not in localhost) and it works perfectly. Can you please check if don't work with this URL?
https://codi.link/PCFET0NUWVBFIGh0bWw+DQo8aHRtbCBsYW5nPSJlbiI+DQo8aGVhZD4NCiAgICA8bWV0YSBjaGFyc2V0PSJVVEYtOCI+DQogICAgPG1ldGEgbmFtZT0idmlld3BvcnQiIGNvbnRlbnQ9IndpZHRoPWRldmljZS13aWR0aCwgaW5pdGlhbC1zY2FsZT0xLjAiPg0KICAgIDx0aXRsZT5FeGFtcGxlPC90aXRsZT4NCjwvaGVhZD4NCjxib2R5Pg0KICAgIDxwcmUgaWQ9ImNvZGUiPjwvcHJlPg0KPC9ib2R5Pg0KPC9odG1sPg==%7CI2NvZGUgew0KICAgIGZvbnQtZmFtaWx5OiAiTW9ub3NwYWNlIjsNCn0NCg0KYm9keSB7DQogICAgY29sb3I6IHJnYigyMDksIDE5OCwgMTk4KTsNCiAgICBiYWNrZ3JvdW5kOiByZ2IoMjQsIDI0LCAyNCkNCn0=%7CZmV0Y2goJ2h0dHBzOi8vanNvbnBsYWNlaG9sZGVyLnR5cGljb2RlLmNvbS9wb3N0cy8xJykNCiAgLnRoZW4ocmVzID0+IHJlcy5qc29uKCkpDQogIC50aGVuKGRhdGEgPT4gew0KICAgICAgZG9jdW1lbnQuZ2V0RWxlbWVudEJ5SWQoImNvZGUiKS5pbm5lclRleHQgPSBKU09OLnN0cmluZ2lmeShkYXRhLCBudWxsLCAyKQ0KICAgfSkNCiAgIC5jYXRjaChlcnIgPT4gY29uc29sZS5lcnJvcihlcnIpKQ==

**Comment by AngelNext** [comment]
It works thx
