### ISSUE TITLE
Add colors for jsdoc comments

### ISSUE THREAD

**Issue by angelnext** [midudev/codi.link#31]
Currently jsdoc comments in codi.link are like this

![image](https://user-images.githubusercontent.com/79442303/132049005-18475fe7-8259-4112-8dbb-2be3787432a2.png)

But in vscode they are like this

![image](https://user-images.githubusercontent.com/79442303/132048923-785a5877-7e81-41f0-b74f-46f318c7d526.png)

As you can see vscode comments have colors and are more readable

**Comment by javigaralva** [comment]
Maybe this is related with Monaco themes.

**Comment by QuevedoIB** [comment]
![jsdocs red](https://user-images.githubusercontent.com/45363951/135894414-79a97c29-cc7d-4fde-a668-9f69f2ebca14.png)
![jsdocs2](https://user-images.githubusercontent.com/45363951/135894419-69a7ae40-87ea-4d6f-ba8a-6c299e45d02e.png)

Can confirm issue is theme related and is fixed in #83
