### ISSUE TITLE
Logo 

### ISSUE THREAD

**Issue by yasielhp** [midudev/codi.link#36]
Quisiera aportar un poco a este proyecto con algunas ideas de logos que he creado:
https://www.figma.com/file/MIQZNfWzVwsHBRC5PGFxrm/Codilink?node-id=0%3A1

**Comment by yasielken** [comment]
He actualizado los logos con diferentes paletas de colores, para que la comunidad elija...

**Comment by YeiserDeveloper** [comment]
A mi me gusta este:

![IMG_20230712_235512.jpg](https://github.com/midudev/codi.link/assets/97372908/611d4efc-9293-4ebe-a543-c729f561682e)

Me parece sencillo y bonito. Te recomiendo hacerlo sin las letras.
