### ISSUE TITLE
I broke codilink page

### ISSUE THREAD

**Issue by edglo98** [midudev/codi.link#46]
I was testing some code and everything was working but, when I try to share my link, the page not working.
I dont know what happen but this is the [link](https://codi.link/PGRpdiA+DQogICAgPGgxIHN0eWxlPSItLWh0bWxjb2xvcjogI0UzNEYyNiI+DQogICAgICAgIEhvbGEgbXVuZG9vDQogICAgPC9oMT4gDQo8L2Rpdj4=|ZGl2IHsNCiAgICBoZWlnaHQ6IDEwMHZoOw0KICAgIGRpc3BsYXk6IGdyaWQ7DQogICAgcGxhY2UtaXRlbXM6IGNlbnRlcjsNCn0NCiANCmgxIHsNCiAgICAtLWh0bWxjb2xvcjogIzAwMDAwMDsNCiAgICBiYWNrZ3JvdW5kLWNvbG9yOiB2YXIoLS1odG1sY29sb3IsICMwMDApOw0KfQ==|Y29uc3QgY29udmVydFRvUkdCID0gZnVuY3Rpb24oaGV4Q29sb3Ipew0KICAgIGlmKCBoZXhDb2xvci5pbmNsdWRlcygnIycpICkgaGV4Q29sb3IgPSBoZXhDb2xvci5yZXBsYWNlKCcjJywnJykNCiAgICBpZiggaGV4Q29sb3IubGVuZ3RoICE9IDYgKSB0aHJvdyAiT25seSBzaXgtZGlnaXQgaGV4IGNvbG9ycyBhcmUgYWxsb3dlZC4iDQogICAgDQogICAgdmFyIGFSZ2JIZXggPSBoZXhDb2xvci5tYXRjaCgvLnsxLDJ9L2cpDQoNCiAgICB2YXIgYVJnYiA9IFsNCiAgICAgICAgcGFyc2VJbnQoYVJnYkhleFswXSwgMTYpLA0KICAgICAgICBwYXJzZUludChhUmdiSGV4WzFdLCAxNiksDQogICAgICAgIHBhcnNlSW50KGFSZ2JIZXhbMl0sIDE2KQ0KICAgIF0NCg0KICAgIHJldHVybiBhUmdiDQp9DQoNCmZ1bmN0aW9uIGdldENvbnRyYXN0Q29sb3IgKHIsZyxiKSB7DQogICAgY29uc3QgW3JlZCwgZ3JlZW4sIGJsdWVdID0gT2JqZWN0LnZhbHVlcyhhcmd1bWVudHMpDQogICAgY29uc3QgY29udHJhc3RUb1ZhbHVhdGUgPSByZWQqMC4yOTkgKyBncmVlbiowLjU4NyArIGJsdWUqMC4xMTQNCiAgICBjb25zdCBoaWdoZXJDb250cmFzdENvbG9yID0gY29udHJhc3RUb1ZhbHVhdGUgPiAxODYgPyAnIzAwMDAwMCcgOiAnI2ZmZmZmZicNCg0KICAgIHJldHVybiBoaWdoZXJDb250cmFzdENvbG9yIA0KfQ0KDQpjb25zdCAkaDEgPSBkb2N1bWVudC5xdWVyeVNlbGVjdG9yKCdoMScpDQpjb25zdCBiZ0NvbG9yID0gJGgxLnN0eWxlLmNzc1RleHQNCiAgICAuc3BsaXQoJyAnKVsxXQ0KICAgIC5yZXBsYWNlKCc7JywnJykNCg0KJGgxLnN0eWxlLmNvbG9yID0gZ2V0Q29udHJhc3RDb2xvciguLi5jb252ZXJ0VG9SR0IoYmdDb2xvcikpDQoNCg0K)

This should be the content:
![imagen](https://user-images.githubusercontent.com/52474257/134264664-c0524eec-754b-4ffa-b169-70a3538e6616.png)

Check the console error jeje 😅

**Comment by Caresle** [comment]
I opened the link and show the content in the screenshot. I check the link in Brave (Chromium 93) and Firefox (92) and i only see warning messages in the console.

Brave:

![image](https://user-images.githubusercontent.com/66541547/134440418-4c62ca98-ca16-414b-bfc1-4cf88ae5b27d.png)

**Comment by edglo98** [comment]
> I opened the link and show the content in the screenshot. I check the link in Brave (Chromium 93) and Firefox (92) and i only see warning messages in the console.
> 
> 
> 
> Brave:
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/66541547/134440418-4c62ca98-ca16-414b-bfc1-4cf88ae5b27d.png)
> 
> 

Yes, today I opened the link and it worked. I Don't know whats happened.  The error in console said something like: "string contains unexpected character"
