### ISSUE TITLE
Write a better README

### ISSUE THREAD

**Issue by midudev** [midudev/codi.link#54]
Right now, README is empty. Maybe writing some documentation for the project would be nice.

**Comment by Caresle** [comment]
Hi, i'm trying to add a `how to install` section to the readme, so i clone, install dependencies of the project and run `npm run dev`.
The project looks to run without problems, but vite is in devDependencies, so i don't know if in the readme i need:

1. Add only `npm i`
or
2. Add `npm i` and `npm i -D`

**Comment by ushieru** [comment]
Can I work on this?

**Comment by Caresle** [comment]
@ushieru Yes, you can. There is no open pull request for this issue right now
