### ISSUE TITLE
Home page for recent codilink projects

### ISSUE THREAD

**Issue by dartilesm** [midudev/codi.link#89]
The base path `./`, should be show the recent projects and maybe other relevant information.

**Comment by JepriCreations** [comment]
I'm thinking, considering the current design and purpose of the app, might be better to introduce a side menu that houses a history feature, kind of like ChatGPT's style but keep it hidden under an icon in the left bar. I'll give it a chance at building this and then run it by midu to see if he's down for adding it to the app.
